### ISSUE TITLE
kubernetes ingress prefixed routing example

### ISSUE THREAD

**Issue by majidaldo** [voila-dashboards/voila#1035]
Here's the essense of how i got it to work on Azure Kubernetes Service with their Application Gateway Controller.  Configuration hell!
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voila
  namespace: jupyter
spec:
  selector:
    matchLabels:
      app: voila
  template:
    metadata:
      labels:
        app: voila
    spec:
      containers:

      - image: dashboard
        name: voila
        command: ['voila']
        args:
          - "--VoilaConfiguration.extension_language_mapping '.py'='python' "
          - --debug
          - --autoreload=True
          - --MappingKernelManager.cull_interval=60
          - --base_url=/dev/voila/
          - --no-browser
        ports:
          - containerPort: 8866 # just for doc?

---
apiVersion: v1
kind: Service
metadata:
  name: voila
  namespace: jupyter
spec:
  selector:
    app: voila
  ports:
  - port: 8866


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jupyter
  namespace: jupyter
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    cert-manager.io/cluster-issuer: letsencrypt-staging
    acme.cert-manager.io/http01-edit-in-place: "true" #https://github.com/jetstack/cert-manager/issues/4547
    appgw.ingress.kubernetes.io/backend-path-prefix: /dev/voila/ # https://azure.github.io/application-gateway-kubernetes-ingress/annotations/#backend-path-prefix, https://stackoverflow.com/questions/67573856/ingress-is-not-working-for-application-gateway-ingress-controller-agic-add-on 'rewrites'
    # but no ingress.kubernetes.io/add-base-url
    ingress.kubernetes.io/add-base-url: "true"
spec:
  tls:
  - hosts:
      - host
    secretName: ingress-cert
  rules:
    - host: host
      http:
        paths:
        - path: /dev/voila/* # need the asterisk!!!!!! undocumented!!!!
          pathType: Prefix
          backend:
            service:
              name: voila
              port:
                number: 8866
```
