### ISSUE TITLE
Voila Renders bqplot Hover Padded 

### ISSUE THREAD

**Issue by yasirroni** [voila-dashboards/voila#694]
Voila renders bqplot automatically padded on hover, while it is not in notebook. The padding also persistent when forced using `padding = '0px 0px 0px 0px'` and `margin= '0px 0px 0px 0px'`.

![image](https://user-images.githubusercontent.com/48709672/92329659-11571580-f093-11ea-9564-90ea9386cd77.png)
![image](https://user-images.githubusercontent.com/48709672/92329661-187e2380-f093-11ea-8e22-b1aa8df98e32.png)

The repo is [here](https://github.com/yasirroni/IPython/blob/master/notebooks/ipywidgets/tooltip%20in%20bqplot.ipynb)

**Comment by yasirroni** [comment]
Inspect element on tooltip:
![image](https://user-images.githubusercontent.com/48709672/92393593-51c59a80-f14a-11ea-9a73-57b3d8d1a990.png)

Still, I didn't get the bug source.

**Comment by yasirroni** [comment]
Found the trouble-maker. Can anyone fit it?

![image](https://user-images.githubusercontent.com/48709672/92395304-56d81900-f14d-11ea-8702-eaeeda806344.png)

**Comment by yasirroni** [comment]
This might help for anyone interested to fix:

![image](https://user-images.githubusercontent.com/48709672/92401406-c8b56000-f157-11ea-855f-d5e7bd918eb9.png)

**Comment by yasirroni** [comment]
Workaround for now:

Customize your own template or edit index.css of the default template:

Location of the default template: \AppData\Local\Programs\Python\Python37\share\jupyter\voila\templates\default\static\index.css

edit .jp-OutputPrompt to:

```css
.jp-OutputPrompt {
  flex: 0 0 var(--jp-cell-prompt-width);
  color: var(--jp-cell-outprompt-font-color);
  font-family: var(--jp-cell-prompt-font-family);
  padding: var(--jp-code-padding);
  letter-spacing: var(--jp-cell-prompt-letter-spacing);
  line-height: var(--jp-code-line-height);
  font-size: var(--jp-code-font-size);
  border: var(--jp-border-width) solid transparent;
  opacity: var(--jp-cell-prompt-opacity);
  /* Right align prompt text, don't wrap to handle large prompt numbers */
  text-align: right;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  /* Disable text selection */
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
  display: none;
}
```

For mybinder.org, you need to make your own index.css template.

My question then: will adding `display: none` cause another bug? Who is responsible in adding this (jupyter, voilay, voila-vuetify)?
