### ISSUE TITLE
Tornado error 403 on voila standalone app

### ISSUE THREAD

**Issue by DeadlySup** [voila-dashboards/voila#816]
Hello everyone,

I'm currently facing issues moving my notebook rendering from jupyter server to voila as a standalone application. The main offenders seem to be ipywidgets and qgrid.

The app is running in a docker based environment (Host ist Linux, Docker base image is continuum.io/anaconda3)

used versions:
_ipywidgets: 7.5.1_
_qgrid: 1.3.1_
_voila: 0.1.21_
_tornado: 6.0.3_

example.ipynb
Cell 1
```
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.rand(3,5))
display(df)
```

Cell 2

```
import qgrid
print('importing qgrid: ', qgrid.__version__)
```

Cell 3

```
qg = qgrid.QGridWidget(df=df, show_toolbar=False)
display('executed cell 3', qg)
```
Cell 4

```
qg = qgrid.QGridWidget(df=df, show_toolbar=True)
display('executed cell 4', qg)
```
Cell 5
```
import ipywidgets as widgets
text = widgets.Label(value="Test")
btn = widgets.Button(description="Test Button")
box = widgets.VBox([text, btn])
display(box)
```

nginx.conf
`
events {
}

http {
	map $http_upgrade $connection_upgrade {
		default upgrade;
		'' close;
	}

	log_format compression '$remote_addr - $remote_user [$time_local] '
	'"$request" $status $body_bytes_sent '
	'"$http_referer" "$http_user_agent" "$gzip_ratio"';

	map $uri $loggable {
		default 1;
		~*\.(ico|css|js|gif|jpg|jpeg|png|svg|woff|woff2|ttf|eot)$ 0;
	}

	access_log /var/log/nginx/access.log compression if=$loggable;

	geo $allow_docker {
		default       0;
		172.18.0.0/16 1;
	}

	# Redirect HTTP to HTTPS
	server {
		listen         80;
		server_name    _;
		return         301 https://$host$request_uri;

	}

	# reverse proxy
	server {
		listen 443 ssl;
		server_name <>;
		ssl_verify_depth 3;
		ssl_protocols TLSv1.1 TLSv1.2;
		# Use <> certificates
		ssl_certificate <>;
		ssl_certificate_key <>;
		large_client_header_buffers 4 64k;
		
		location /proxy/ {
			include /etc/nginx/snippets/auth.conf;
			include /etc/nginx/snippets/proxy-headers.conf;
			
		location /proxy/voila/ {
				set $upstream http://voila;
				proxy_pass $upstream;
				proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
				proxy_set_header X-Real-IP $remote_addr;
				proxy_http_version 1.1;
				proxy_buffering off;
				proxy_set_header Upgrade $http_upgrade;
				proxy_set_header Connection "upgrade";
				proxy_read_timeout 86400;
				client_max_body_size 100M;
		
		location /proxy/jupyter/ {
                set $upstream http://jupyter;
				proxy_pass $upstream;
				proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
				proxy_set_header X-Real-IP $remote_addr;
				proxy_set_header Host $http_host;
				proxy_http_version 1.1;
				proxy_redirect off;
				proxy_buffering off;
				proxy_set_header Upgrade $http_upgrade;
				proxy_set_header Connection "upgrade";
				proxy_read_timeout 86400;
			}
`

docker-compose.yml (tried both nb_extensions enabled and disabled, didn't change the rendering)
```

voila:
    image: don/anaconda-red:0.2.6
    container_name: voila
    ports:
      - 8866:8866
    hostname: voila
    extra_hosts:
      - "device-proxy:172.0.0.1"
    user: 0:357
    working_dir: /root/.notebooks/
    volumes:
      - /var/don/jupyter:/root/.notebooks
      - /var/don/node-red:/root/.node-red/
      - shared:/root/.shared
    entrypoint: /bin/bash -c
    command: |
      '/opt/conda/bin/jupyter trust /root/.notebooks/*.ipynb && \ 
      /opt/conda/bin/voila /root/.notebooks/--no-browser \
      --enable_nbextensions=True --base_url /proxy/voila/ --port 80'
      
    restart: unless-stopped
```

rendered via jupyter server extension (qgrid rendering was achieved with #75 )
![image](https://user-images.githubusercontent.com/36188613/105723449-1411b480-5f27-11eb-9840-19c45b073298.png)

rendered via voila standalone. You can see that the dataframe and strings are rendered properly, the rest is not
![image](https://user-images.githubusercontent.com/36188613/105724267-f5f88400-5f27-11eb-907a-e083b950cd9b.png)

Voila Messages in commandline
![image](https://user-images.githubusercontent.com/36188613/105724489-3526d500-5f28-11eb-9369-2a386c8b2d34.png)

I also professionally analyzed the output of the web console and highlighted the similarities between jupyter server (left) and voila standalone (right)
![image](https://user-images.githubusercontent.com/36188613/105722654-30612180-5f26-11eb-861b-3c936794c415.png)

the first two rows disappeared when I copied the nbextensions_configurator folder from /op/conda/lib/python3.7/site-packages/jupyter_nbextensions_configurator/static to /opt/conda/share/jupyter/nbextensions. I don't know if this was correct to do, but it didn't change the outputs, just two errors less in the console.

So this leaves the 403 coming from tornado, which indicates that a request (from nginx I'd suppose) was refused by the voila server. I checked the local jupyter configuration and perhaps the difference is, that jupyter listens on all ip addresses and allows root+remote access. I have not found similar settings for voila in the configuration... At this point I'm more confused than anything, because it renders some parts, but not others.

Any help, questions or ideas on what to try are appreciated.
